### PR TITLE
[v2.0.0] BREAKING: Switch to Platform

### PR DESCRIPTION
**Pull request by AlexanderBabel**
Hey,

I converted this plugin from an accessory to a platform due to HomeKit limitations. If you want to use multiple TVs on the same HomeBridge instance, you'll need to expose them as external accessories. This feature is only available for platforms. Therefore I did the conversion.

### Possible use cases: 
1. You have multiple BenQ projectors connected to the same Computer running HomeBridge
2. You are using additional plugins that expose a TV

This is a big **breaking change**. Thus I increased the version number to v2.0.0 and wrote a short upgrade guide in the readme file.

### CODE REVIEW

**Comment by solowalker27** [comment]
Sorry for the delay. Thanks for the work. I had started to do something similar myself. I'll merge this PR into a branch and test it out. I assume you've been running this yourself since you submitted the PR? Any bugs or other changes you'd want to commit before merging and publishing?

**Comment by AlexanderBabel** [comment]
Thanks! Yes I used it in the meantime. Until now there were no issues whatsoever. Just worked like a charm. Nonetheless I suggest you to test it by yourself, maybe I forgot something or maybe it's only working with my setup. I don't know.

If you encounter any problems, feel free to write me.

**Comment by solowalker27** [comment]
I pushed one change and I've been using it since. No other issues. I may merge and release it soon. 👍

**Comment by AlexanderBabel** [comment]
Hey, any news on the release of the 2.0 version?

**Comment by solowalker27** [comment]
Sorry, I've I had computer problems and have just been super busy since then. Still on my to-do list.

**Comment by solowalker27** [comment]
Merged into master and released.

**Pull request merged**
